import React, { forwardRef } from 'react'
import { useGLTF } from '@react-three/drei'

export const DroneModel = forwardRef((props, ref) => {
  const { nodes, materials } = useGLTF('./DJI.glb')
  return (
<group ref={ref} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane012.geometry}
        material={materials.Back_Popella_Engine}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane012_1.geometry}
        material={materials.Battery}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane012_2.geometry}
        material={materials['Body overall']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane012_3.geometry}
        material={materials.Front_Joint}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane012_4.geometry}
        material={materials.Back_Joint}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane012_5.geometry}
        material={materials.Back_Handle_Carbonfiber}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane012_6.geometry}
        material={materials.Back_Joint_grip}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane012_7.geometry}
        material={materials['Back_Popella_Engine 002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane012_8.geometry}
        material={materials.Back_Popella}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane012_9.geometry}
        material={materials['Back_Popella_Engine_Glass and light']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane012_10.geometry}
        material={materials.Front_Popella_Engine}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane012_11.geometry}
        material={materials.Front_Handle_Carbonfiber}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane012_12.geometry}
        material={materials.Front_Joint_grip}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane012_13.geometry}
        material={materials['Front_Popella_Engine 002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane012_14.geometry}
        material={materials.Front_Popella}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane012_15.geometry}
        material={materials['Front_Popella_Engine_Glass and light']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane012_16.geometry}
        material={materials.Front_Body}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane012_17.geometry}
        material={materials.Front_Mesh}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane012_18.geometry}
        material={materials.Covering}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane012_19.geometry}
        material={materials.Front_Legs}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane012_20.geometry}
        material={materials.Back_Cover}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane012_21.geometry}
        material={materials['Front Screws and Grip']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane012_22.geometry}
        material={materials.Round_Thing}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane012_23.geometry}
        material={materials.Back_Tail}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane012_24.geometry}
        material={materials.Back_Top_Beneath}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane012_25.geometry}
        material={materials.Camera}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane012_26.geometry}
        material={materials['Camera sub parts']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane012_27.geometry}
        material={materials.Camera_Lens}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane012_28.geometry}
        material={materials.Bottom_Part}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane012_29.geometry}
        material={materials.Back_Legs}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane012_30.geometry}
        material={materials.Top_Center_Part}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane012_31.geometry}
        material={materials.Bottom_Lens}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane012_32.geometry}
        material={materials.Top_Lens}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane012_33.geometry}
        material={materials.Front_Lens}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane012_34.geometry}
        material={materials.Top_lens_glass}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane012_35.geometry}
        material={materials['Top_lens_glass.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane012_36.geometry}
        material={materials.Side_Lens}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane012_37.geometry}
        material={materials.Back_Lens}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane012_38.geometry}
        material={materials.grey}
      />
    </group>
  )
})

useGLTF.preload('./DJI.glb')
